name: vardrobe
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  animated_text_kit: ^2.0.0
  simple_animations: ^2.2.3
  font_awesome_flutter: ^8.10.0
  flutter_snake_navigationbar: ^0.4.1+3
  flutter_page_transition: ^0.1.6
  carousel_pro: ^1.0.0
  flutter_rating_bar: ^3.2.0
  curved_navigation_bar: ^0.3.4
  carousel_slider: ^2.3.1
  toast: ^0.1.5
  move_to_background: ^1.0.1
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  provider: ^4.3.3
  email_validator: '^1.0.5'
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^2.0.1
  flutter_spinkit: "^4.1.2"
  ars_progress_dialog: ^0.1.2
  cloud_firestore: ^1.0.0
  flutter_datetime_picker: ^1.5.0
  firebase_storage: ^8.0.0
  image_picker: ^0.7.2
  image_cropper: ^1.3.1
  cached_network_image: ^3.0.0-nullsafety
  algolia: ^1.0.1
  share: ^2.0.1
  hover_effect: ^0.6.0
  stripe_payment: ^1.0.11
  http: ^0.13.1
  url_launcher: ^6.0.3
  arcore_flutter_plugin: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0

flutter_native_splash:
  color: "#1e1f28"
  opacity: 0.7

flutter:


  uses-material-design: true

  assets:
    - Assets/images/
  fonts:
    - family: Nunito-Regular
      fonts:
        - asset: Assets/fonts/Nunito-Regular.ttf
    - family: Nunito-Bold
      fonts:
        - asset: Assets/fonts/Nunito-Bold.ttf
          weight: 600
    - family: Nunito-BoldItalic
      fonts:
        - asset: Assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Nunito-Italic
      fonts:
        - asset: Assets/fonts/Nunito-Italic.ttf
          weight: 300
          style: italic



